version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.12
    working_directory: /go/src/github.com/flowerinthenight/kubepfm/
    steps:
    - checkout
    - run:
        name: build
        shell: /bin/bash
        command: |
          GO111MODULE=on go build -v
